/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyxe;

import java.awt.Component;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import quanlyxe.xuly.*;
import quanlyxe.thucthe.*;

/**
 *
 * @author BND6699
 */
public class Banhang extends javax.swing.JFrame {

    phieuxuatTT selectedPhieuXuat = null;
    ct_phieuxuatTT selectedPhieuXuatCT = null;
    ct_phieuxuatXL phieuXuatCTServices = new ct_phieuxuatXL();
    hoadonTT selectedHoaDon = null;
    ct_hoadonTT selectedCTHoaDon = null;
    ct_hoadonXL ct_hoadonservices = new ct_hoadonXL();

    sanphamXL sanphamServices = new sanphamXL();
    phieuxuatXL phieuxuatServices = new phieuxuatXL();
    hoadonXL hoadonServices = new hoadonXL();

    ArrayList<ct_phieuxuatTT> dsPhieuXuatCT = new ArrayList<ct_phieuxuatTT>();
    ArrayList<phieuxuatTT> dsPX = new ArrayList<phieuxuatTT>();
    ArrayList<ct_hoadonTT> dsCTHoaDon = new ArrayList<>();
    ArrayList<hoadonTT> dsHoaDon = new ArrayList<>();
    ArrayList<soluongTT> dsSoluong = new ArrayList<>();
    ArrayList<sanphamTT> dsSanpham = new ArrayList<sanphamTT>();
    ArrayList<banhangTT> dsBanhang = new ArrayList<banhangTT>();
    ArrayList<tongtienTT> dsTongTien = new ArrayList<>();

    public Banhang() {
        initComponents();
        loadSanpham();
        showData();
        txt_soluong.setText("1");
        txt_sdt.setText("0");
        txt_giamgia.setText("0");
        
        String MaHD = txt_ma.getText().trim();
        showDataList(MaHD);
        showThanhTien(MaHD);
        showTong(MaHD);

        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String strDate = formatter.format(date);
        System.out.println(strDate);

        txt_ngay.setText(strDate);
    }

    public void setTenUser(String username) {
        this.txt_tennhanvien.setText(username);
        System.out.println(username);
    }

    public void showSoluong(String MaSP) {
        //load data
        ArrayList<soluongTT> list = phieuXuatCTServices.getSoluong(MaSP);
        dsSoluong = list;

        for (int i = 0; i < list.size(); i++) {
            txt_soluongcon.setText(String.valueOf((list.get(i).getSoLuong())));
            System.out.println(list.get(i).getSoLuong());
        }
    }

    public void loadSanpham() {
        txt_masp.removeAllItems();
        dsSanpham = sanphamServices.getAllRecords();
        for (sanphamTT item : dsSanpham) {
            txt_masp.addItem(item);
        }
        //jcbAuthor = new JComboBox(new DefaultComboBoxModel(authors));
        txt_masp.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof sanphamTT) {
                    sanphamTT sanpham = (sanphamTT) value;
                    setText(String.valueOf(sanpham.getName()));
                }
                return this;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableData = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ngay = new javax.swing.JLabel();
        txt_tennhanvien = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_so = new javax.swing.JLabel();
        btn_hoadonmoi = new javax.swing.JButton();
        btn_thanhtoan = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_kho = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_soluongcon = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_dongia = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_masp = new javax.swing.JComboBox<>();
        txt_soluong = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_thanhtien = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ghichu = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_giamgia = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_tongtien = new javax.swing.JLabel();
        btn_inhoadon = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();

        setTitle("Bán hàng");
        setResizable(false);

        jPanelHeader1.setBackground(java.awt.SystemColor.activeCaption);
        jPanelHeader1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BÁN HÀNG");
        jLabel2.setIconTextGap(10);

        javax.swing.GroupLayout jPanelHeader1Layout = new javax.swing.GroupLayout(jPanelHeader1);
        jPanelHeader1.setLayout(jPanelHeader1Layout);
        jPanelHeader1Layout.setHorizontalGroup(
            jPanelHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeader1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(307, 307, 307))
        );
        jPanelHeader1Layout.setVerticalGroup(
            jPanelHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeader1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(jTableData);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Tên nhân viên:");

        jLabel3.setText("Ngày:");

        txt_ngay.setText("00/00/0000");

        txt_tennhanvien.setText("Null");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ngay)
                    .addComponent(txt_tennhanvien))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_tennhanvien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ngay)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Mã hóa đơn:");

        txt_ma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ma.setForeground(new java.awt.Color(255, 51, 0));
        txt_ma.setText("00");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Số:");

        txt_so.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_so.setText("00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_so)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_ma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_so))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btn_hoadonmoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/hoadon.png"))); // NOI18N
        btn_hoadonmoi.setText("Hóa đơn mới");
        btn_hoadonmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hoadonmoiActionPerformed(evt);
            }
        });

        btn_thanhtoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/chi.png"))); // NOI18N
        btn_thanhtoan.setText("Thanh toán");
        btn_thanhtoan.setEnabled(false);
        btn_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thanhtoanActionPerformed(evt);
            }
        });

        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/backup.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.setEnabled(false);
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_kho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_kho.setText("Null");

        jLabel7.setText("Kho:");

        jLabel6.setText("Tên sản phẩm");

        jLabel8.setText("Số lượng còn:");

        txt_soluongcon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_soluongcon.setForeground(new java.awt.Color(255, 51, 0));
        txt_soluongcon.setText("000");

        jLabel9.setText("Đơn giá:");

        txt_dongia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_dongia.setText("000");

        jLabel10.setText("Số lượng");

        txt_masp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maspActionPerformed(evt);
            }
        });

        jLabel11.setText("Tổng tiền sản phẩm:");

        txt_thanhtien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_thanhtien.setText("000");

        jLabel12.setText("Số điện thoại");

        txt_ghichu.setColumns(20);
        txt_ghichu.setRows(5);
        jScrollPane2.setViewportView(txt_ghichu);

        jLabel13.setText("Ghi chú");

        jLabel14.setText("Giảm giá");

        jLabel15.setText("Tổng tiền hóa đơn:");

        txt_tongtien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_tongtien.setText("000");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_masp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_soluong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_sdt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txt_giamgia)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_thanhtien)
                            .addComponent(txt_tongtien))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_dongia))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_soluongcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_kho, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_soluongcon)
                    .addComponent(jLabel8)
                    .addComponent(txt_masp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_kho))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(txt_dongia))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_giamgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_thanhtien)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt_tongtien))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        btn_inhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/print.png"))); // NOI18N
        btn_inhoadon.setText("In hóa đơn");
        btn_inhoadon.setEnabled(false);
        btn_inhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inhoadonActionPerformed(evt);
            }
        });

        btn_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/close1.png"))); // NOI18N
        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/xoa.png"))); // NOI18N
        btn_xoa.setText("Xóa sản phẩm");
        btn_xoa.setEnabled(false);
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btn_thoat)
                            .addComponent(btn_xoa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_hoadonmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(btn_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_inhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_hoadonmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_inhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_thoat)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        long DonGia = Long.valueOf(txt_dongia.getText().trim().replaceAll("\\.", "").replaceAll(",", ""));
        int SoLuong = Integer.valueOf(txt_soluong.getText().trim());
        long Tien = SoLuong * DonGia;

        String maPX = txt_ma.getText().trim();
        String MaHD = txt_ma.getText().trim();

        sanphamTT masp = (sanphamTT) txt_masp.getSelectedItem();
        int SoLuongCon = Integer.valueOf(txt_soluongcon.getText().trim());
        String kho = txt_kho.getText().trim();

        if (SoLuong > SoLuongCon || SoLuong <= 0) {
            JOptionPane.showMessageDialog(null, "Số lượng không đủ!","Thông báo",JOptionPane.WARNING_MESSAGE);
        } else {
            int rowEffected1 = ct_hoadonservices.AddNewRecord(MaHD, masp.getID(), SoLuong, Tien);
            int rowEffected2 = phieuXuatCTServices.AddNewRecord(maPX, kho, masp.getID(), SoLuong);

            if (rowEffected1 > 0) {
                if (rowEffected2 > 0) {
                    int rowEffected3 = phieuXuatCTServices.AddNewRecord2(maPX, kho, masp.getID(), SoLuong);
                    if (rowEffected3 > 0) {
                        showDataList(maPX);
                        showTong(MaHD);
                        showThanhTien(MaHD);
                        showSoluong(masp.getID());
                        JOptionPane.showMessageDialog(null, "Thêm thành công!");
                        btn_thanhtoan.setEnabled(true);
                    }
                }
            } else {
                showDataList(maPX);
                showTong(MaHD);
                showThanhTien(MaHD);
                JOptionPane.showMessageDialog(null, "Thêm thất bại (Do sai hoặc đã tồn tại)");
            }
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void txt_maspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maspActionPerformed

        sanphamTT masp = (sanphamTT) txt_masp.getSelectedItem();

        txt_kho.setText(masp.getSupplierID());
        System.out.println(masp.getSupplierID());

        showSoluong(masp.getID());
        System.out.println(masp.getName());

        Locale localeEN = new Locale("en", "EN");
        NumberFormat en = NumberFormat.getInstance(localeEN);

        long giaban = masp.getPrice();
        String str1 = en.format(giaban);
        txt_dongia.setText(str1);
    }//GEN-LAST:event_txt_maspActionPerformed

    public void showTong(String MaHD) {
        //load data

        ArrayList<hoadonTT> list = hoadonServices.getTong(MaHD);
        dsHoaDon = list;

        Locale localeEN = new Locale("en", "EN");
        NumberFormat en = NumberFormat.getInstance(localeEN);

        for (int i = 0; i < list.size(); i++) {
            txt_tongtien.setText(String.valueOf(en.format(list.get(i).getTongTien())));

            System.out.println(list.get(i).getMaHoaDon());
            System.out.println(list.get(i).getTongTien());
        }
    }

    public void showThanhTien(String MaHD) {
        //load data

        ArrayList<tongtienTT> list = ct_hoadonservices.getTong(MaHD);
        dsTongTien = list;

        Locale localeEN = new Locale("en", "EN");
        NumberFormat en = NumberFormat.getInstance(localeEN);

        for (int i = 0; i < list.size(); i++) {
            txt_thanhtien.setText(String.valueOf(en.format(list.get(i).getTongTien())));
            System.out.println(list.get(i).getTongTien());
        }
    }

    public void showData() {
        //load data
        ArrayList<hoadonTT> list = hoadonServices.getAllRecords();
        dsHoaDon = list;

        for (int i = 0; i < list.size(); i++) {
            int getMHD = Integer.valueOf(list.get(i).getMaHoaDon());
            int MHD = getMHD;
            txt_ma.setText(String.valueOf(MHD));
            System.out.println(MHD);
        }
    }

    public void showDataList(String MaHD) {

        DefaultTableModel model = (DefaultTableModel) this.jTableData.getModel();
        model.setRowCount(0);

        //load data
        ArrayList<banhangTT> list = ct_hoadonservices.getRecords(MaHD);
        dsBanhang = list;

        Locale localeEN = new Locale("en", "EN");
        NumberFormat en = NumberFormat.getInstance(localeEN);

        Object[] row = new Object[7];

        for (int i = 0; i < list.size(); i++) {

            row[0] = list.get(i).getMaCTHoaDon();
            row[1] = list.get(i).getMaSP();
            row[2] = list.get(i).getTenSP();
            row[3] = list.get(i).getSoLuong();
            row[4] = en.format(list.get(i).getDongia());

            model.addRow(row);
        }

        ListSelectionModel cellSelectionModel = jTableData.getSelectionModel();
        cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //Dang ky event click tren danh sach        
        cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                //goi ham show data chi tiet
                gridSelectedChanged(e);
            }
        });
    }

    public void gridSelectedChanged(ListSelectionEvent e) {
        String selectedData = null;
        String selectedID = "";  //Mã chi tiết hóa đơn

        int[] selectedRows = jTableData.getSelectedRows();
        int[] selectedColumns = jTableData.getSelectedColumns();

        int selectedRow = jTableData.getSelectedRow();
        int selectedColumn = jTableData.getSelectedColumn();

        System.out.println("selectedRow: " + selectedRow);
        System.out.println("selectedColumn: " + selectedColumn);

        if (selectedRow >= 0 && selectedColumn >= 0) {
            selectedData = String.valueOf(jTableData.getValueAt(selectedRow, selectedColumn));
            selectedID = (String) jTableData.getValueAt(selectedRow, 0);
            //Find chi tiết hóa đơn
            selectedCTHoaDon = findCTHoaDon(selectedID, dsCTHoaDon);

            System.out.println("Selected: " + selectedData + " , MaHoaDon: " + selectedID);

            showDataDetail(selectedID);
        }
    }

    private void showDataDetail(String MaCTHoaDon) {
        txt_so.setText(MaCTHoaDon);
    }

    public ct_hoadonTT findCTHoaDon(String MaCTHoaDon, ArrayList<ct_hoadonTT> cT_HoaDons) {
        for (ct_hoadonTT item : cT_HoaDons) {
            if (item.getMaCTHoaDon().equals(MaCTHoaDon)) {
                return item;
            }
        }
        return null;
    }

    private void btn_hoadonmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hoadonmoiActionPerformed

        Date date = new Date();
        ArrayList<hoadonTT> list = hoadonServices.getAllRecords();
        dsHoaDon = list;

        String soPX = txt_ma.getText().trim();
        String User = txt_tennhanvien.getText().trim();

        String MaHoaDon = txt_ma.getText().trim();
        String GhiChu = txt_ghichu.getText().trim();
        String SDT = txt_sdt.getText().trim();
        long TongTien = 0;

        int rowEffected1 = hoadonServices.AddNewRecord(date, SDT, TongTien, User, GhiChu);
        int rowEffected2 = phieuxuatServices.AddNewRecord(User, date);

        if (rowEffected1 > 0) {
            if (rowEffected1 > 0) {
                JOptionPane.showMessageDialog(null, "Tạo thành công!");
                showData();

                int MHD = Integer.valueOf(MaHoaDon);
                int MHDnew = MHD + 1;
                showDataList(String.valueOf(MHDnew));
                System.out.println("Hóa đơn mới: " + MHDnew);

                txt_tongtien.setText("000");
                txt_giamgia.setText("0");
                txt_thanhtien.setText("000");
                txt_so.setText("00");
                btn_them.setEnabled(true);
                btn_xoa.setEnabled(true);
                btn_inhoadon.setEnabled(false);
                btn_thanhtoan.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Tạo thất bại");
            }
        }
    }//GEN-LAST:event_btn_hoadonmoiActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        sanphamTT masp = (sanphamTT) txt_masp.getSelectedItem();
        String MaCTHoaDon = txt_so.getText().trim();
        String maCTPX = txt_so.getText().trim();
        String MaHoaDon = txt_ma.getText().trim();

        int input = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa sản phẩm số " + MaCTHoaDon + " không?", "Confirmation...",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (input == 0) {
            //Xoa
            int rowEffected1 = ct_hoadonservices.DeleteRecord(MaCTHoaDon, MaHoaDon);
            int rowEffected2 = phieuXuatCTServices.DeleteRecord(maCTPX, masp.getID());

            if (rowEffected1 > 0) {
                if (rowEffected2 > 0) {
                    JOptionPane.showMessageDialog(null, "Xóa thành công!");
                    showSoluong(masp.getID());
                    showDataList(MaHoaDon);
                    showTong(MaHoaDon);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Xóa thất bại");
            }
        }

    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thanhtoanActionPerformed

        String SDT = txt_sdt.getText().trim();
        if (SDT.equals("")) {
            JOptionPane.showMessageDialog(null, "Điền số điện thoại");
        } else {
            Date date = new Date();
            ArrayList<hoadonTT> list = hoadonServices.getAllRecords();
            dsHoaDon = list;

            String soPX = txt_ma.getText().trim();
            String User = txt_tennhanvien.getText().trim();

            String MaHoaDon = txt_ma.getText().trim();
            String GhiChu = txt_ghichu.getText().trim();
            String TT = txt_thanhtien.getText().trim().replaceAll("\\.", "").replaceAll(",", "");
            String GG = txt_giamgia.getText().trim();

            long ThanhTien = Integer.valueOf(TT);
            long GiamGia = Integer.valueOf(GG);
            long TongTien = ThanhTien - ((ThanhTien / 100) * GiamGia);

            System.out.println(TongTien);

            int rowEffected = hoadonServices.UpdateRecord(MaHoaDon, date, SDT, TongTien, User, GhiChu);
            if (rowEffected > 0) {
                JOptionPane.showMessageDialog(null, "Thanh toán thành công!");
                showTong(MaHoaDon);
                showThanhTien(MaHoaDon);
                btn_them.setEnabled(false);
                btn_xoa.setEnabled(false);
                btn_inhoadon.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "Thanh toán thất bại");
            }
        }
    }//GEN-LAST:event_btn_thanhtoanActionPerformed

    private void btn_inhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inhoadonActionPerformed
        int MaHD = Integer.valueOf(txt_ma.getText().trim());
        XuatHoaDon(MaHD);
    }//GEN-LAST:event_btn_inhoadonActionPerformed
    
    public void XuatHoaDon(int MaHD)
    {
        try {
            ketnoi_sql sql = new ketnoi_sql();
            Hashtable map = new Hashtable();
            JasperDesign jd = JRXmlLoader.load("G:\\BuiNgocDuy\\QuanLyXe\\src\\quanlyxe\\baocao\\XuatHoaDon.jrxml");       
            JasperReport jr = JasperCompileManager.compileReport("G:\\BuiNgocDuy\\QuanLyXe\\src\\quanlyxe\\baocao\\XuatHoaDon.jrxml");  
            
            map.put("MaHoaDon",MaHD);
            JasperPrint jp = JasperFillManager.fillReport(jr, map, sql.getConnection());
            JasperViewer.viewReport(jp,false);     
            JasperExportManager.exportReportToPdfFile(jp,"G:\\BuiNgocDuy\\QuanLyXe\\src\\quanlyxe\\baocao\\XuatHoaDon.pdf");
                  
        } catch (ClassNotFoundException | SQLException | JRException e) {
            JOptionPane.showMessageDialog(null, "Cannot show report" + e.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(Sanpham.class.getName()).log(Level.SEVERE, null, ex);
            
        }     
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banhang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hoadonmoi;
    private javax.swing.JButton btn_inhoadon;
    private javax.swing.JButton btn_thanhtoan;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelHeader1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableData;
    private javax.swing.JLabel txt_dongia;
    private javax.swing.JTextArea txt_ghichu;
    private javax.swing.JTextField txt_giamgia;
    private javax.swing.JLabel txt_kho;
    private javax.swing.JLabel txt_ma;
    private javax.swing.JComboBox<sanphamTT> txt_masp;
    private javax.swing.JLabel txt_ngay;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JLabel txt_so;
    private javax.swing.JTextField txt_soluong;
    private javax.swing.JLabel txt_soluongcon;
    private javax.swing.JLabel txt_tennhanvien;
    private javax.swing.JLabel txt_thanhtien;
    private javax.swing.JLabel txt_tongtien;
    // End of variables declaration//GEN-END:variables
}
